#ifndef ANDROIDCAMERAFRAMEWORK_OPENGLMODELRECTANGLE_H
#define ANDROIDCAMERAFRAMEWORK_OPENGLMODELRECTANGLE_H

#include "OpenGLModel.h"

class OpenGLModelRectangle : public OpenGLModel {
};

#endif //ANDROIDCAMERAFRAMEWORK_OPENGLMODELRECTANGLE_H
